{% set name = "pyomeca" %}
{% set version = "v1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ba19c36c260da866c3bda69a3aebffc84646c90aeafe30ae191937cb7fdaae4e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools
    - python >=3
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib-base
    - scipy
    - {{ pin_compatible('ezc3d') }}
    - xlrd
    - xarray
    - bottleneck

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - make test

about:
  home: http://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_file: LICENSE.md
  summary: 'Pyomeca is a python library allowing to carry out a complete biomechanical analysis; in a simple, logical and concise way'
  description: |
    Python toolbox for biomechanics analysis
  doc_url: https://pyomeca.github.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - romainmartinez
    - pariterre
