{% set name = "pyomeca" %}
{% set version = "v1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3270d4fd8f800bb4d590eb08f1cb734c8421671e1e4bb8d5394c828d8f8326f8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools
    - python >=3
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib-base
    - scipy
    - {{ pin_compatible('ezc3d') }}
    - xlrd
    - xarray
    - bottleneck

test:
  imports: 
    - pyomeca

about:
  home: http://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_file: LICENSE.md
  summary: 'Pyomeca is a python library allowing to carry out a complete biomechanical analysis; in a simple, logical and concise way'
  description: |
    Python toolbox for biomechanics analysis
  doc_url: https://pyomeca.github.io
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - romainmartinez
    - pariterre
