{% set name = "pyomeca" %}
{% set version = "2019.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9aaf95300fe14c6ca800fe7ffed3a40e2abd8ae9de76f5928b8a62436bd6294b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools
    - python >=3
    - pip
  run:
    - python
    - numpy
    - pandas
    - matplotlib
    - scipy
    - ezc3d

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests

about:
  home: http://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Pyomeca is a python library allowing to carry out a complete biomechanical analysis; in a simple, logical and concise way'
  description: |
    Python toolbox for biomechanics analysis
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - mrtnz
    - pariterre
