{% set name = "pyomeca" %}
{% set version = "2019.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: eda26f0a975c00eb0549fa47e61a0e721d43c98ce0223a4f3363651d8f4c5603

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - setuptools
    - python >=3
    - pip
  run:
    - python
    - numpy
    - pandas
    - matplotlib
    - scipy
    - ezc3d
    - xlrd

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest tests

about:
  home: http://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Pyomeca is a python library allowing to carry out a complete biomechanical analysis; in a simple, logical and concise way'
  description: |
    Python toolbox for biomechanics analysis
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - romainmartinez
    - pariterre
