{% set owner = "pyomeca" %}
{% set name = "pyomeca" %}
{% set version = "2024.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ owner }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 79ac3507a2c77195d12df591572ba58ef644b84bf5952a00d3dc48e056d5eab1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib-base
    - scipy
    - {{ pin_compatible('ezc3d') }}
    - openpyxl
    - xarray
    - bottleneck

test:
  imports:
    - pyomeca

about:
  home: http://github.com/{{ owner }}/{{ name }}
  license: Apache-2.0
  license_file: LICENSE.md
  summary: Pyomeca is a python library allowing to carry out a complete biomechanical analysis; in a simple, logical and concise way
  description: |
    Python toolbox for biomechanics analysis
  doc_url: https://pyomeca.github.io
  dev_url: https://github.com/{{ owner }}/{{ name }}

extra:
  recipe-maintainers:
    - romainmartinez
    - pariterre
