{% set owner = "pyomeca" %}
{% set name = "pyomeca" %}
{% set version = "2021.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ owner }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fc44d72027fd1908c4706b7df708c32edc2e2da14b54387d741b8b3dcd6ff2e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - setuptools
    - python >=3
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - matplotlib-base
    - scipy
    - {{ pin_compatible('ezc3d') }}
    - xlrd
    - xarray
    - bottleneck

test:
  imports:
    - pyomeca

about:
  home: http://github.com/{{ owner }}/{{ name }}
  license: Apache-2.0
  license_file: LICENSE.md
  summary: Pyomeca is a python library allowing to carry out a complete biomechanical analysis; in a simple, logical and concise way
  description: |
    Python toolbox for biomechanics analysis
  doc_url: https://pyomeca.github.io
  dev_url: https://github.com/{{ owner }}/{{ name }}

extra:
  recipe-maintainers:
    - romainmartinez
    - pariterre
