travis:
  secure:
    BINSTAR_TOKEN: WKQ1Ld3noEBp6UV0uW2mj4xcMBOwiF4lAAJTBNXWyicCb4zwf/GKQeb8+eC2KUtiGyJmhXrhcln34g/XrgvSPAANe2teEiy/sNxegni72wUCTeKCtfw6RSk+jxtWuo0UKIvL2vbY7NYRgdoTW1nic5lKElK49dDD/s+jd85owUaKrlENsSDp2ul0/gp3PYk7DRd82WTrF/bipuTq9a3r8V9IC5oFJ0KCyVb4/+sk7NnuZH3b931p+uoDos+pj8IdC8xIeBjT/K1UYToU/hAM+oxJc++WSGjsJO5Hu/hpr4RUtHiZ7AkrR2tyF833u0MsTG47LrG894WLg9DJ35aAFnuxg2gNttFp3KDqPy+bEmLoEScMBfhh6ZSSZrLWgYnpkwc8kydJ8v3Pw+TulOYtjO0EQFHfse6a6zzJasX8ew2gIdXq8p4WcWiT8SQLu/TeuES0eekyoreIM6w7hXA9CI6++lJ98dxPmPgCxpT2YM9nSLZik029Z8oZLUnDZQw0/MSMaVlf6IYhTKeTjJJDkpFrRUzG8CLfficqSSvSDMr/ivlhO91/3loUWgy8qsUKC7/4MNET8Qa1MtMMaISWhekpNU0ETweY/Gbs8Ftv3lcmuowXnnU+YHahTE+dCts0ZL/nFMOzQ485eijxRdrEuU5TOSsyPqR3Sk6L/V5R7YM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
